image: node:stretch

stages:
  - build

cache:
  paths:
    - node_modules/


###################
#      BUILD      #
###################

build:
  stage: build
  artifacts:
    expire_in: 2 hours
    paths:
      - dist
  script:
    - npm install --progress=false
    - npm run build


###################
#       TEST      #
###################
