image: node:latest

stages:
  - install
  - build


install:
  stage: install
  script:
    - npm i
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules/


build:
  stage: build
  script:
    - npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - dist/

